include theos/makefiles/common.mk

LIBRARY_NAME = Nexus
Nexus_FILES = Nexus.mm \
    NexusViewController.mm \
    NexusPrefsController.mm \
    LPGL/LPUtil.mm \
    LPGL/LPVector2.mm \
    LPGL/LPVector3.mm \
    LPGL/LPMatrix4.mm \
    LPGL/LPGLViewController.mm 

Nexus_INSTALL_PATH = /Library/LivePapers/Plugins
Nexus_FRAMEWORKS = UIKit CoreGraphics OpenGLES GLKit

include $(THEOS_MAKE_PATH)/library.mk
