include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = LPWebKit
LPWebKit_INSTALL_PATH = /Library/LivePapers/Plugins
LPWebKit_FRAMEWORKS = UIKit
LPWebKit_OBJCFLAGS = -I../common 
LPWebKit_FILES = LPWebKit.m \
				 LPWebKitController.m \

include $(THEOS_MAKE_PATH)/library.mk
