include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = LPBuiltins
LPBuiltins_INSTALL_PATH = /Library/LivePapers/Plugins
LPBuiltins_FRAMEWORKS = UIKit CoreGraphics
LPBuiltins_FILES = LPBuiltins.m \
                   LPDefaultViewController.m \

include $(THEOS_MAKE_PATH)/library.mk
