#define LCPrefsPath @"/var/mobile/Library/Preferences/org.porkholt.livepapers.plist"
#define LCDefaultPaper @"org.porkholt.livepapers.default"
#define LCPrefsHomeKey @"HomeWallpaper"
#define LCPrefsLockKey @"LockWallpaper"
#define LCCenterUDReloadItems @"ReloadItems"
#define LCCenterUDPrefsItems @"PrefsItems"
#define LCCenterName @"org.porkholt.livepapers.center"
#define LCCenterMessageReload @"reloadSettings"
#define LCCenterMessagePrefs @"reloadPreferences"
#define LCWallpapersPath @"/Library/LivePapers/Wallpapers"
#define LCPluginsPath @"/Library/LivePapers/Plugins"
#define LCBuiltinPrefsPath @"/var/mobile/Library/Preferences/org.porkholt.livepapers.builtinprefs.plist"
#define LCBuiltinPrefsSolidColor @"LCSolidColor"
#define LCBuiltinPrefsSolidColorDefaultRed   0.203f
#define LCBuiltinPrefsSolidColorDefaultGreen 0.325f
#define LCBuiltinPrefsSolidColorDefaultBlue  0.533f
